import './globals.css'
import type { Metadata } from 'next'
import { Spline_Sans_Mono } from 'next/font/google'
import Head from 'next/head'

const spline = Spline_Sans_Mono({
  subsets: ['latin'],
  variable: '--font-spline',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${spline.variable}`}>{children}</body>
    </html>
  )
}
